local _, Addon = ...

local Keys = Addon.PreferenceKeys
local L = Addon.L

local BACKGROUND_PANEL = "background"

--- Every preference the addon exposes, as data.
--- Adding an entry here is enough for it to be persisted and to show up in the
--- options panel; no adapter needs to change.
---@type Preference[]
local PreferenceCatalog = {
	{
		key = Keys.OWN_TRACKER_ENABLED,
		kind = "boolean",
		default = true,
		label = L.PREF_OWN_TRACKER,
		tooltip = L.PREF_OWN_TRACKER_TIP,
	},
	{
		key = Keys.KEEP_BLIZZARD_TRACKER,
		kind = "boolean",
		default = false,
		label = L.PREF_KEEP_BLIZZARD,
		tooltip = L.PREF_KEEP_BLIZZARD_TIP,
	},
	{
		key = Keys.TRACKER_WIDTH,
		page = L.PAGE_APPEARANCE,
		kind = "number",
		default = 320,
		label = L.PREF_WIDTH,
		tooltip = L.PREF_WIDTH_TIP,
		minimum = 220,
		maximum = 520,
		step = 10,
	},
	{
		key = Keys.TRACKER_HEIGHT,
		page = L.PAGE_APPEARANCE,
		kind = "number",
		default = 420,
		label = L.PREF_HEIGHT,
		tooltip = L.PREF_HEIGHT_TIP,
		minimum = 200,
		maximum = 900,
		step = 20,
	},
	{
		key = Keys.EDIT_MODE,
		page = L.PAGE_APPEARANCE,
		kind = "boolean",
		default = false,
		label = L.PREF_EDIT_MODE,
		tooltip = L.PREF_EDIT_MODE_TIP,
	},
	{
		key = Keys.TRACKER_SCALE,
		page = L.PAGE_APPEARANCE,
		kind = "number",
		default = 100,
		label = L.PREF_SCALE,
		tooltip = L.PREF_SCALE_TIP,
		minimum = 60,
		maximum = 150,
		step = 5,
	},
	{
		key = Keys.PANEL_OPACITY,
		page = L.PAGE_APPEARANCE,
		kind = "number",
		default = 88,
		label = L.PREF_PANEL_OPACITY,
		tooltip = L.PREF_PANEL_OPACITY_TIP,
		minimum = 0,
		maximum = 100,
		step = 4,
	},
	{
		key = Keys.FONT_SIZE,
		page = L.PAGE_APPEARANCE,
		kind = "number",
		default = 12,
		label = L.PREF_FONT_SIZE,
		tooltip = L.PREF_FONT_SIZE_TIP,
		minimum = 8,
		maximum = 20,
		step = 1,
	},
	{
		key = Keys.FONT_NAME,
		page = L.PAGE_APPEARANCE,
		kind = "string",
		default = "Friz Quadrata TT",
		label = L.PREF_FONT,
		tooltip = L.PREF_FONT_TIP,
		choicesKey = "fonts",
	},
	{
		key = Keys.FONT_FLAG,
		page = L.PAGE_APPEARANCE,
		kind = "string",
		default = "none",
		label = L.PREF_FONT_FLAG,
		tooltip = L.PREF_FONT_FLAG_TIP,
		choices = Addon.FontFlags.Choices,
	},
	{
		key = Keys.FONT_SHADOW,
		page = L.PAGE_APPEARANCE,
		kind = "boolean",
		default = true,
		label = L.PREF_FONT_SHADOW,
		tooltip = L.PREF_FONT_SHADOW_TIP,
	},
	{
		key = Keys.WRAP_LONG_TEXT,
		page = L.PAGE_APPEARANCE,
		kind = "boolean",
		default = true,
		label = L.PREF_WRAP_TEXT,
		tooltip = L.PREF_WRAP_TEXT_TIP,
	},
	{
		key = Keys.BACKGROUND_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Solid",
		label = L.PREF_BACKGROUND_TEXTURE,
	},
	{
		key = Keys.BACKGROUND_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "color",
		default = "050509",
		label = L.PREF_BACKGROUND_COLOR,
	},
	{
		key = Keys.BACKGROUND_INSET,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_BACKGROUND_INSET,
		minimum = 0,
		maximum = 10,
		step = 1,
	},
	{
		key = Keys.BORDER_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Solid",
		label = L.PREF_BORDER_TEXTURE,
	},
	{
		key = Keys.BORDER_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "color",
		default = "333029",
		label = L.PREF_BORDER_COLOR,
	},
	{
		key = Keys.BORDER_CLASS_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_BORDER_CLASS_COLOR,
	},
	{
		key = Keys.BORDER_THICKNESS,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 1,
		label = L.PREF_BORDER_THICKNESS,
		minimum = 1,
		maximum = 24,
		step = 1,
	},
	{
		key = Keys.PROGRESS_BAR_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Blizzard",
		label = L.PREF_PROGRESS_BAR_TEXTURE,
	},
	{
		key = Keys.BORDER_OPACITY,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 90,
		label = L.PREF_BORDER_OPACITY,
		minimum = 0,
		maximum = 100,
		step = 5,
	},
	{
		key = Keys.SHOW_FILTER_BUTTON,
		page = L.PAGE_BUTTONS,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_FILTER_BUTTON,
		tooltip = L.PREF_SHOW_FILTER_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_ACHIEVEMENT_BUTTON,
		page = L.PAGE_BUTTONS,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_ACHIEVEMENT_BUTTON,
		tooltip = L.PREF_SHOW_ACHIEVEMENT_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_MINIMAP_BUTTON,
		page = L.PAGE_BUTTONS,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_MINIMAP_BUTTON,
		tooltip = L.PREF_SHOW_MINIMAP_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_ITEM_BUTTONS,
		page = L.PAGE_BUTTONS,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_ITEM_BUTTONS,
		tooltip = L.PREF_SHOW_ITEM_BUTTONS_TIP,
	},
	{
		key = Keys.SORT_MODE,
		page = L.PAGE_CONTENT,
		kind = "string",
		default = "none",
		label = L.PREF_SORT_MODE,
		tooltip = L.PREF_SORT_MODE_TIP,
		choices = Addon.SortModes,
	},
	{
		key = Keys.COMPLETED_AT_TOP,
		page = L.PAGE_CONTENT,
		kind = "boolean",
		default = false,
		label = L.PREF_COMPLETED_AT_TOP,
		tooltip = L.PREF_COMPLETED_AT_TOP_TIP,
	},
	{
		key = Keys.EVENTS_ENABLED,
		page = L.PAGE_CONTENT,
		kind = "boolean",
		default = true,
		label = L.PREF_EVENTS_ENABLED,
		tooltip = L.PREF_EVENTS_ENABLED_TIP,
	},
	{
		key = Keys.BONUS_ZONE_WIDE,
		page = L.PAGE_CONTENT,
		kind = "boolean",
		default = false,
		label = L.PREF_BONUS_ZONE_WIDE,
		tooltip = L.PREF_BONUS_ZONE_WIDE_TIP,
	},
	{
		key = Keys.SOUND_ENABLED,
		page = L.PAGE_SOUND,
		kind = "boolean",
		default = true,
		label = L.PREF_SOUND_ENABLED,
		tooltip = L.PREF_SOUND_ENABLED_TIP,
	},
	{
		key = Keys.SOUND_QUEST_COMPLETE,
		page = L.PAGE_SOUND,
		kind = "string",
		default = "questComplete",
		label = L.PREF_SOUND_QUEST_COMPLETE,
		tooltip = L.PREF_SOUND_QUEST_COMPLETE_TIP,
		choicesKey = "sounds",
	},
	{
		key = Keys.SOUND_CHANNEL,
		page = L.PAGE_SOUND,
		kind = "string",
		default = "Master",
		label = L.PREF_SOUND_CHANNEL,
		tooltip = L.PREF_SOUND_CHANNEL_TIP,
		choices = Addon.SoundChannels,
	},
	{
		key = Keys.ANNOUNCE_ON_LOAD,
		page = L.PAGE_ADVANCED,
		kind = "boolean",
		default = true,
		label = L.PREF_ANNOUNCE_ON_LOAD,
		tooltip = L.PREF_ANNOUNCE_ON_LOAD_TIP,
	},
}

Addon.PreferenceCatalog = PreferenceCatalog
