local _, Addon = ...

local Keys = Addon.PreferenceKeys
local L = Addon.L

local FRAME_PANEL = "frame"
local INTEGRATION_PANEL = "integration"
local APPEARANCE_PANEL = "appearance"
local CONTENT_PANEL = "content"

--- Every preference the addon exposes, as data.
--- Adding an entry here is enough for it to be persisted and to show up in the
--- options panel; no adapter needs to change.
---@type Preference[]
local PreferenceCatalog = {
	{
		key = Keys.OWN_TRACKER_ENABLED,
		kind = "boolean",
		default = true,
		label = L.PREF_OWN_TRACKER,
		tooltip = L.PREF_OWN_TRACKER_TIP,
	},
	{
		key = Keys.KEEP_BLIZZARD_TRACKER,
		kind = "boolean",
		default = false,
		label = L.PREF_KEEP_BLIZZARD,
		tooltip = L.PREF_KEEP_BLIZZARD_TIP,
	},
	{
		key = Keys.TRACKER_WIDTH,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 320,
		label = L.PREF_WIDTH,
		tooltip = L.PREF_WIDTH_TIP,
		minimum = 220,
		maximum = 520,
		step = 10,
	},
	{
		key = Keys.TRACKER_HEIGHT,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 420,
		label = L.PREF_HEIGHT,
		tooltip = L.PREF_HEIGHT_TIP,
		minimum = 200,
		maximum = 900,
		step = 20,
	},
	{
		key = Keys.EDIT_MODE,
		panel = APPEARANCE_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_EDIT_MODE,
		tooltip = L.PREF_EDIT_MODE_TIP,
	},
	{
		key = Keys.TRACKER_SCALE,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 100,
		label = L.PREF_SCALE,
		tooltip = L.PREF_SCALE_TIP,
		minimum = 60,
		maximum = 150,
		step = 5,
	},
	{
		key = Keys.PANEL_OPACITY,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 88,
		label = L.PREF_PANEL_OPACITY,
		tooltip = L.PREF_PANEL_OPACITY_TIP,
		minimum = 0,
		maximum = 100,
		step = 4,
	},
	{
		key = Keys.FONT_SIZE,
		panel = APPEARANCE_PANEL,
		kind = "number",
		default = 12,
		label = L.PREF_FONT_SIZE,
		tooltip = L.PREF_FONT_SIZE_TIP,
		minimum = 8,
		maximum = 20,
		step = 1,
	},
	{
		key = Keys.FONT_NAME,
		panel = APPEARANCE_PANEL,
		kind = "string",
		default = "Inter",
		label = L.PREF_FONT,
		tooltip = L.PREF_FONT_TIP,
		choicesKey = "fonts",
	},
	{
		key = Keys.FONT_FLAG,
		panel = APPEARANCE_PANEL,
		kind = "string",
		default = "none",
		label = L.PREF_FONT_FLAG,
		tooltip = L.PREF_FONT_FLAG_TIP,
		choices = Addon.FontFlags.Choices,
	},
	{
		key = Keys.FONT_SHADOW,
		panel = APPEARANCE_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_FONT_SHADOW,
		tooltip = L.PREF_FONT_SHADOW_TIP,
	},
	{
		key = Keys.WRAP_LONG_TEXT,
		panel = APPEARANCE_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WRAP_TEXT,
		tooltip = L.PREF_WRAP_TEXT_TIP,
	},
	{
		key = Keys.BACKGROUND_TEXTURE,
		panel = FRAME_PANEL,
		kind = "string",
		default = "Solid",
		label = L.PREF_BACKGROUND_TEXTURE,
	},
	{
		key = Keys.BACKGROUND_COLOR,
		panel = FRAME_PANEL,
		kind = "color",
		default = "050509",
		label = L.PREF_BACKGROUND_COLOR,
	},
	{
		key = Keys.BACKGROUND_INSET,
		panel = FRAME_PANEL,
		kind = "number",
		default = 0,
		label = L.PREF_BACKGROUND_INSET,
		minimum = 0,
		maximum = 10,
		step = 1,
	},
	{
		key = Keys.BORDER_TEXTURE,
		panel = FRAME_PANEL,
		kind = "string",
		default = "Solid",
		label = L.PREF_BORDER_TEXTURE,
	},
	{
		key = Keys.BORDER_COLOR,
		panel = FRAME_PANEL,
		kind = "color",
		default = "333029",
		label = L.PREF_BORDER_COLOR,
	},
	{
		key = Keys.BORDER_CLASS_COLOR,
		panel = FRAME_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_BORDER_CLASS_COLOR,
	},
	{
		key = Keys.BORDER_THICKNESS,
		panel = FRAME_PANEL,
		kind = "number",
		default = 1,
		label = L.PREF_BORDER_THICKNESS,
		minimum = 1,
		maximum = 24,
		step = 1,
	},
	{
		key = Keys.PROGRESS_BAR_TEXTURE,
		panel = FRAME_PANEL,
		kind = "string",
		default = "Blizzard",
		label = L.PREF_PROGRESS_BAR_TEXTURE,
	},
	{
		key = Keys.PROGRESS_BAR_STYLE,
		panel = FRAME_PANEL,
		kind = "string",
		default = Addon.ProgressBarStyles.OWN,
		label = L.PREF_PROGRESS_BAR_STYLE,
		tooltip = L.PREF_PROGRESS_BAR_STYLE_TIP,
		choices = Addon.ProgressBarStyles.Choices,
	},
	{
		key = Keys.PROGRESS_BAR_HEIGHT,
		panel = FRAME_PANEL,
		kind = "number",
		default = 12,
		label = L.PREF_PROGRESS_BAR_HEIGHT,
		tooltip = L.PREF_PROGRESS_BAR_HEIGHT_TIP,
		minimum = 8,
		maximum = 24,
		step = 1,
	},
	{
		key = Keys.BORDER_OPACITY,
		panel = FRAME_PANEL,
		kind = "number",
		default = 90,
		label = L.PREF_BORDER_OPACITY,
		minimum = 0,
		maximum = 100,
		step = 5,
	},
	{
		key = Keys.SHOW_FILTER_BUTTON,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_FILTER_BUTTON,
		tooltip = L.PREF_SHOW_FILTER_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_ACHIEVEMENT_BUTTON,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_ACHIEVEMENT_BUTTON,
		tooltip = L.PREF_SHOW_ACHIEVEMENT_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_INTEGRATION_BUTTON,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_INTEGRATION_BUTTON,
		tooltip = L.PREF_SHOW_INTEGRATION_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_MINIMAP_BUTTON,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_MINIMAP_BUTTON,
		tooltip = L.PREF_SHOW_MINIMAP_BUTTON_TIP,
	},
	{
		key = Keys.SHOW_ITEM_BUTTONS,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SHOW_ITEM_BUTTONS,
		tooltip = L.PREF_SHOW_ITEM_BUTTONS_TIP,
	},
	{
		key = Keys.SORT_MODE,
		panel = CONTENT_PANEL,
		kind = "string",
		default = "none",
		label = L.PREF_SORT_MODE,
		tooltip = L.PREF_SORT_MODE_TIP,
		choices = Addon.SortModes,
	},
	{
		key = Keys.COMPLETED_AT_TOP,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_COMPLETED_AT_TOP,
		tooltip = L.PREF_COMPLETED_AT_TOP_TIP,
	},
	{
		key = Keys.EVENTS_ENABLED,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_EVENTS_ENABLED,
		tooltip = L.PREF_EVENTS_ENABLED_TIP,
	},
	{
		key = Keys.WORLD_QUESTS_ENABLED,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_WORLD_QUESTS_ENABLED,
		tooltip = L.PREF_WORLD_QUESTS_ENABLED_TIP,
	},
	{
		key = Keys.INSTANCE_FOCUS,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_INSTANCE_FOCUS,
		tooltip = L.PREF_INSTANCE_FOCUS_TIP,
	},
	{
		key = Keys.BONUS_ZONE_WIDE,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_BONUS_ZONE_WIDE,
		tooltip = L.PREF_BONUS_ZONE_WIDE_TIP,
	},
	{
		key = Keys.SOUND_ENABLED,
		panel = CONTENT_PANEL,
		kind = "boolean",
		default = true,
		label = L.PREF_SOUND_ENABLED,
		tooltip = L.PREF_SOUND_ENABLED_TIP,
	},
	{
		key = Keys.SOUND_QUEST_COMPLETE,
		panel = CONTENT_PANEL,
		kind = "string",
		default = "questComplete",
		label = L.PREF_SOUND_QUEST_COMPLETE,
		tooltip = L.PREF_SOUND_QUEST_COMPLETE_TIP,
		choicesKey = "sounds",
	},
	{
		key = Keys.SOUND_CHANNEL,
		panel = CONTENT_PANEL,
		kind = "string",
		default = "Master",
		label = L.PREF_SOUND_CHANNEL,
		tooltip = L.PREF_SOUND_CHANNEL_TIP,
		choices = Addon.SoundChannels,
	},
	{
		key = Keys.ANNOUNCE_ON_LOAD,
		kind = "boolean",
		default = true,
		label = L.PREF_ANNOUNCE_ON_LOAD,
		tooltip = L.PREF_ANNOUNCE_ON_LOAD_TIP,
	},
	{
		key = Keys.TOMTOM_ENABLED,
		panel = INTEGRATION_PANEL,
		kind = "boolean",
		default = false,
		label = L.PREF_TOMTOM,
	},
}

Addon.PreferenceCatalog = PreferenceCatalog
