std = "lua51"
max_line_length = false

exclude_files = {
	"Libs/",
	"dist/",
	"Tests/",
}

ignore = {
	-- Mixins and objects take self without always using it.
	"212/self",
}

-- Written by the addon: the saved variables table, the binding strings the
-- client reads, and the two handlers Bindings.xml calls.
globals = {
	"AuraTrackerQuestorDB",
	"AuraTrackerQuestor_OpenOptions",
	"AuraTrackerQuestor_ToggleTracker",
	"BINDING_HEADER_AURATRACKERQUESTOR",
	"BINDING_NAME_AURATRACKERQUESTOR_OPTIONS",
	"BINDING_NAME_AURATRACKERQUESTOR_TOGGLE",
	"SLASH_AURATRACKERQUESTOR1",
}

-- Read from the game.
read_globals = {
	"ACCEPT",
	"ACHIEVEMENT_BUTTON",
	"ADVENTURE_TRACKING_MODULE_HEADER_TEXT",
	"AchievementFrame",
	"AchievementFrame_LoadUI",
	"AchievementFrame_SelectAchievement",
	"AchievementFrame_ToggleAchievementFrame",
	"CANCEL",
	"C_AddOns",
	"C_AreaPoiInfo",
	"C_ChallengeMode",
	"C_ContentTracking",
	"C_CurrencyInfo",
	"C_EventScheduler",
	"C_Map",
	"C_NeighborhoodInitiative",
	"C_PerksActivities",
	"C_QuestInfoSystem",
	"C_QuestLog",
	"C_Scenario",
	"C_ScenarioInfo",
	"C_SuperTrack",
	"C_TaskQuest",
	"C_Timer",
	"C_TradeSkillUI",
	"Constants",
	"CreateFrame",
	"DEFAULT_CHAT_FRAME",
	"EVENTS_LABEL",
	"EncounterJournal",
	"EncounterJournal_LoadUI",
	"Enum",
	"EventRegistry",
	"FILTER",
	"GameTooltip",
	"GetAchievementCategory",
	"GetAchievementCriteriaInfo",
	"GetAchievementInfo",
	"GetAchievementNumCriteria",
	"GetCategoryInfo",
	"GetCategoryList",
	"GetCoinTextureString",
	"GetNumQuestLogChoices",
	"GetNumQuestLogRewards",
	"GetQuestDifficultyColor",
	"GetQuestLogChoiceInfo",
	"GetQuestLogChoiceInfoLootType",
	"GetQuestLogCompletionText",
	"GetQuestLogQuestText",
	"GetQuestLogRewardInfo",
	"GetQuestLogRewardMoney",
	"GetQuestLogSpecialItemInfo",
	"GetQuestUiMapID",
	"GetRealmName",
	"GetTaskInfo",
	"GetTasksTable",
	"GetWorldElapsedTime",
	"GetWorldElapsedTimers",
	"InCombatLockdown",
	"IsLoggedIn",
	"Item",
	"LFGListUtil_FindQuestGroup",
	"LibStub",
	"MenuUtil",
	"MicroButtonTooltipText",
	"MonthlyActivitiesFrame_OpenFrameToActivity",
	"OBJECTIVES_SHOW_QUEST_MAP",
	"OBJECTIVES_STOP_TRACKING",
	"OBJECTIVES_VIEW_ACHIEVEMENT",
	"OBJECTIVES_VIEW_IN_QUESTLOG",
	"OBJECTIVES_VIEW_IN_TRAVELERS_LOG",
	"ObjectiveTrackerFrame",
	"PROFESSIONS_CRAFTING_FORM_RECRAFTING_HEADER",
	"PROFESSIONS_TRACKER_HEADER_PROFESSION",
	"PROFESSIONS_TRACKER_REAGENT_COUNT_FORMAT",
	"PROFESSIONS_TRACKER_REAGENT_FORMAT",
	"PROFESSIONS_TRACKER_REAGENT_RANGE_FORMAT",
	"ProfessionsUtil",
	"QUEST_WATCH_QUEST_READY",
	"QuestLogDisplayMode",
	"QuestMapFrame",
	"QuestMapFrame_OpenToQuestDetails",
	"QuestUtil",
	"QuestUtils_IsQuestWatched",
	"QuestUtils_IsQuestWorldQuest",
	"REWARDS",
	"ReloadUI",
	"Settings",
	"SlashCmdList",
	"StaticPopupDialogs",
	"StaticPopup_Show",
	"TRACKER_HEADER_ACHIEVEMENTS",
	"TRACKER_HEADER_BONUS_OBJECTIVES",
	"TRACKER_HEADER_CAMPAIGN_QUESTS",
	"TRACKER_HEADER_DUNGEON",
	"TRACKER_HEADER_INITIATIVE_TASKS",
	"TRACKER_HEADER_MONTHLY_ACTIVITIES",
	"TRACKER_HEADER_QUESTS",
	"TRACKER_HEADER_SCENARIO",
	"TRACKER_HEADER_WORLD_QUESTS",
	"ToggleCollectionsJournal",
	"UIParent",
	"UnitName",
	"strtrim",
	"time",
	"wipe",
}
