return function(Addon, T)
	T.Suite("HexColor", function()
		T.Test("ida e volta preserva a cor", function()
			local red, green, blue = Addon.HexColor.ToRGB("EDC200")
			T.Equals(Addon.HexColor.FromRGB(red, green, blue), "EDC200")
		end)

		T.Test("branco e preto nos extremos", function()
			local red, green, blue = Addon.HexColor.ToRGB("FFFFFF")
			T.Equals(red, 1)
			T.Equals(green, 1)
			T.Equals(blue, 1)
			T.Equals(Addon.HexColor.FromRGB(0, 0, 0), "000000")
		end)

		T.Test("canal ilegivel vira zero em vez de nil", function()
			local red, green, blue = Addon.HexColor.ToRGB("zzzzzz")
			T.Equals(red, 0)
			T.Equals(green, 0)
			T.Equals(blue, 0)
		end)

		T.Test("meio caminho fica proximo de 0.5", function()
			T.Near(Addon.HexColor.ToRGB("808080"), 0.5, 0.01)
		end)

		T.Test("canais nao se misturam", function()
			local red, green, blue = Addon.HexColor.ToRGB("FF0000")
			T.Equals(red, 1)
			T.Equals(green, 0)
			T.Equals(blue, 0)
			T.Equals(Addon.HexColor.FromRGB(0, 1, 0), "00FF00")
		end)
	end)
end
