local _, Addon = ...

local Keys = Addon.PreferenceKeys

local BACKGROUND_PANEL = "background"

--- Every preference the addon exposes, as data.
--- Adding an entry here is enough for it to be persisted and to show up in the
--- options panel; no adapter needs to change.
---@type Preference[]
local PreferenceCatalog = {
	{
		key = Keys.OWN_TRACKER_ENABLED,
		kind = "boolean",
		default = true,
		label = "Rastreador próprio",
		tooltip = "Mostra o rastreador desenhado pelo addon.",
	},
	{
		key = Keys.KEEP_BLIZZARD_TRACKER,
		kind = "boolean",
		default = false,
		label = "Manter o rastreador da Blizzard",
		tooltip = "Deixa os dois na tela ao mesmo tempo. Sem isso, o da Blizzard sai "
			.. "de cena assim que o nosso liga.",
	},
	{
		key = Keys.TRACKER_WIDTH,
		page = "Aparência",
		kind = "number",
		default = 320,
		label = "Largura",
		tooltip = "Largura do rastreador, em pixels.",
		minimum = 220,
		maximum = 520,
		step = 10,
	},
	{
		key = Keys.TRACKER_HEIGHT,
		page = "Aparência",
		kind = "number",
		default = 420,
		label = "Altura",
		tooltip = "Altura do rastreador. O que passar disso é rolado.",
		minimum = 200,
		maximum = 900,
		step = 20,
	},
	{
		key = Keys.EDIT_MODE,
		page = "Aparência",
		kind = "boolean",
		default = false,
		label = "Modo de edição",
		tooltip = "Libera o rastreador para ser arrastado. Fora dele o frame não "
			.. "responde ao mouse, para não sair do lugar sem querer.",
	},
	{
		key = Keys.TRACKER_SCALE,
		page = "Aparência",
		kind = "number",
		default = 100,
		label = "Escala",
		tooltip = "Tamanho geral do rastreador, em porcentagem.",
		minimum = 60,
		maximum = 150,
		step = 5,
	},
	{
		key = Keys.PANEL_OPACITY,
		page = "Aparência",
		kind = "number",
		default = 88,
		label = "Opacidade do painel",
		tooltip = "Transparência do fundo. O texto não é afetado.",
		minimum = 0,
		maximum = 100,
		step = 4,
	},
	{
		key = Keys.FONT_SIZE,
		page = "Aparência",
		kind = "number",
		default = 12,
		label = "Tamanho da fonte",
		tooltip = "Vale para toda a lista.",
		minimum = 8,
		maximum = 20,
		step = 1,
	},
	{
		key = Keys.FONT_NAME,
		page = "Aparência",
		kind = "string",
		default = "Friz Quadrata TT",
		label = "Fonte",
		tooltip = "Fontes registradas por qualquer addon que você use.",
		choicesKey = "fonts",
	},
	{
		key = Keys.FONT_FLAG,
		page = "Aparência",
		kind = "string",
		default = "none",
		label = "Contorno da fonte",
		tooltip = "Contorno ajuda a ler o texto sobre cenário claro.",
		choices = Addon.FontFlags.Choices,
	},
	{
		key = Keys.FONT_SHADOW,
		page = "Aparência",
		kind = "boolean",
		default = true,
		label = "Sombra da fonte",
		tooltip = "Sombra discreta atrás do texto. Alternativa mais leve ao contorno.",
	},
	{
		key = Keys.WRAP_LONG_TEXT,
		page = "Aparência",
		kind = "boolean",
		default = false,
		label = "Quebrar textos longos",
		tooltip = "Desligado, o que não cabe na linha é cortado com reticências e cada "
			.. "missão ocupa menos espaço. O texto inteiro continua no tooltip.",
	},
	{
		key = Keys.BACKGROUND_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Solid",
		label = "Textura do fundo",
	},
	{
		key = Keys.BACKGROUND_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "color",
		default = "050509",
		label = "Cor do fundo",
	},
	{
		key = Keys.BACKGROUND_INSET,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 0,
		label = "Recuo do fundo",
		minimum = 0,
		maximum = 10,
		step = 1,
	},
	{
		key = Keys.BORDER_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Solid",
		label = "Textura da borda",
	},
	{
		key = Keys.BORDER_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "color",
		default = "333029",
		label = "Cor da borda",
	},
	{
		key = Keys.BORDER_CLASS_COLOR,
		panel = BACKGROUND_PANEL,
		kind = "boolean",
		default = false,
		label = "Cor da borda pela classe",
	},
	{
		key = Keys.BORDER_THICKNESS,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 1,
		label = "Espessura da borda",
		minimum = 1,
		maximum = 24,
		step = 1,
	},
	{
		key = Keys.PROGRESS_BAR_TEXTURE,
		panel = BACKGROUND_PANEL,
		kind = "string",
		default = "Blizzard",
		label = "Textura da barra de progresso",
	},
	{
		key = Keys.BORDER_OPACITY,
		panel = BACKGROUND_PANEL,
		kind = "number",
		default = 90,
		label = "Opacidade da borda",
		minimum = 0,
		maximum = 100,
		step = 5,
	},
	{
		key = Keys.SHOW_FILTER_BUTTON,
		page = "Botões",
		kind = "boolean",
		default = true,
		label = "Botão de filtro",
		tooltip = "O botão no canto do cabeçalho que abre o menu de filtros, seções, "
			.. "ordenação e conquistas.",
	},
	{
		key = Keys.SHOW_ACHIEVEMENT_BUTTON,
		page = "Botões",
		kind = "boolean",
		default = true,
		label = "Botão de conquistas",
		tooltip = "Abre o painel de conquistas direto do cabeçalho.",
	},
	{
		key = Keys.SHOW_MINIMAP_BUTTON,
		page = "Botões",
		kind = "boolean",
		default = true,
		label = "Botão do minimapa",
		tooltip = "Clique mostra ou esconde o rastreador; clique direito abre as opções.",
	},
	{
		key = Keys.SHOW_ITEM_BUTTONS,
		page = "Botões",
		kind = "boolean",
		default = true,
		label = "Botões de item das missões",
		tooltip = "O item usável ao lado do nome da missão. É ele que faz o rastreador "
			.. "parar de atualizar em combate; desligado desde o login, isso não acontece.",
	},
	{
		key = Keys.SORT_MODE,
		page = "Conteúdo",
		kind = "string",
		default = "none",
		label = "Ordenação",
		tooltip = "Como ordenar as entradas dentro de cada seção.",
		choices = Addon.SortModes,
	},
	{
		key = Keys.EVENTS_ENABLED,
		page = "Conteúdo",
		kind = "boolean",
		default = true,
		label = "Rastrear eventos",
		tooltip = "Mostra a seção de eventos do mundo.",
	},
	{
		key = Keys.BONUS_ZONE_WIDE,
		page = "Conteúdo",
		kind = "boolean",
		default = false,
		label = "Objetivos bônus da zona inteira",
		tooltip = "Ligado, lista todos os objetivos bônus da zona. Desligado, só os "
			.. "da área onde você está, como o rastreador da Blizzard faz.",
	},
	{
		key = Keys.SOUND_ENABLED,
		page = "Som",
		kind = "boolean",
		default = true,
		label = "Avisar ao concluir",
		tooltip = "Toca um som quando uma missão fica pronta para entregar.",
	},
	{
		key = Keys.SOUND_QUEST_COMPLETE,
		page = "Som",
		kind = "string",
		default = "questComplete",
		label = "Som da missão concluída",
		tooltip = "Sons do jogo, mais os que qualquer addon seu registrar. Escolher "
			.. "um já o toca, para você ouvir antes de fechar.",
		choicesKey = "sounds",
	},
	{
		key = Keys.SOUND_CHANNEL,
		page = "Som",
		kind = "string",
		default = "Master",
		label = "Canal",
		tooltip = "Qual volume das opções de áudio controla esse som.",
		choices = Addon.SoundChannels,
	},
	{
		key = Keys.ANNOUNCE_ON_LOAD,
		page = "Avançado",
		kind = "boolean",
		default = true,
		label = "Anunciar ao carregar",
		tooltip = "Escreve uma linha no chat quando o addon termina de carregar.",
	},
}

Addon.PreferenceCatalog = PreferenceCatalog
